<?php

/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/7/15 0015
 * Time: 上午 12:20
 */
class EmailRecipientCollection extends Collection
{
	public function addItem(EmailRecipient $obj, $key = null)
	{
		parent::addItem($obj, $key); // TODO: Change the autogenerated stub
	}
}